name: bothAsTwoJobs
on: workflow_dispatch
jobs:
  compileAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: maven compile
        run: mvn compile
      - name: maven test
        run: mvn test