name: bothAsTwoSteps
on: workflow_dispatch
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: maven compile
        run: mvn compile
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: maven test
        run: mvn test
